# Do not edit. Generated by the configure script.
export PATH:=/Users/tiims/Documents/web/react-website/.cache/src/node-v14.21.3/files/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/opt/homebrew/opt/python@3.10/bin/python3.10
PREFIX=/Users/tiims/Documents/web/react-website/versions/node/v14.21.3
